spring:
  application:
    name: sa-streaming
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/streaming_app

server:
  port: 8082
  servlet:
    contextPath: /streaming

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
      preferIpAddress: true
